version: '3.8'

services:
    nginx:
        image: nginx:alpine
        container_name: laravel_nginx_zoo
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html:delegated
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app-zoo
        container_name: zoo_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html:delegated
        depends_on:
            - mysql
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        user: "${UID:-1000}:${GID:-1000}"

    mysql:
        image: mysql:8.0
        container_name: zoo_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        ports:
            - "3307:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    cron:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - ./docker/cron/crontab:/etc/cron.d/laravel-scheduler
        command: >
            bash -c "crontab /etc/cron.d/laravel-scheduler && cron -f"
        depends_on:
            - app

volumes:
    mysql_data:
        driver: local

